name: Custom Action
description: 'This composite action will do Cache and Install dependencies'
inputs:
  cache:
    description: 'Need to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  cache-used:
    description: "Cache used or not"
    value: ${{ steps.install-deps.outputs.cache-used }}
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Cache dependencies
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}

    - name: Install Dependencies
      id: install-deps
      run: |
        npm ci
        echo "cache-used=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash