name: Custom Action
description: 'This composite action, will do Checkout, Cache and Install dependencies'
inputs:
  cache:  # id of input
    description: 'Need to cache dependencies or not'
    required: false
    default: 'true'
outputs:
  cache-used:
    description: "Cache used or not"
    value: ${{ steps.install-deps.outputs.cache-used }}
runs:
  using: "composite"
  steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache dependencies
      if: ${{ inputs.cache == 'true' }}
      uses: actions/cache@v3
      id: cache
      with:
        path: ~/.npm
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install Dependencies
      id: install-deps
      if: ${{ cache.outputs.cache-hit != 'true' }} || ${{ inputs.cache != 'true' }}
      run: |
        npm ci
        echo "cache-used=${{ steps.cache.outputs.cache-hit }}" >> $GITHUB_OUTPUT
      shell: bash