name: Deployment Example 1
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm install
    - name: Lint
      run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    steps:
    - name: Checkout1
      uses: actions/checkout@v3
    - name: Install Dependencies
      run: npm install
    - name: Test
      run: npm run test
    - name: Build website
      run: npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: |
          dist
          package.json
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Get build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
    - name: Output content
      run: ls
    - name: Deploy code
      run: echo "Deploying code to server....."