name: Deployment Example 1
on:
  workflow_dispatch:
  pull_request:
    types:
      - opened
  push:
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Cache and Install dependencies
      uses: ./.github/workflows/custWF/depends/
      with:
        cache: false
    - name: Lint
      run: npm run lint
  test:
    needs: [lint]
    runs-on: ubuntu-latest
    outputs:
      script-file: ${{ steps.publish.outputs.script-file }}
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Checkout, Cache and Install dependencies
      uses: ./.github/workflows/custWF/depends/
    - name: Test
      run: npm run test
    - name: Build website
      run: npm run build
    - name: upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: build-artifact
        path: |
          dist
          package.json
    - name: publish JS filename
      id: publish
      run: find dist/assets/*.js -type f -execdir echo 'script-file={}' >> $GITHUB_OUTPUT ';'
  deploy:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
    - name: Get build artifact
      uses: actions/download-artifact@v4
      with:
        name: build-artifact
    - name: Output content
      run: ls
    - name: Output fine name
      run: echo "${{ needs.test.outputs.script-file }}"
    - name: Deploy code
      run: echo "Deploying code to server.."