name: Windows Test WF

on:
  workflow_dispatch

jobs:
  test:
    runs-on: self-hosted
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Print some greetings
        run: echo "Hello, world!"
        shell: pwsh
        
      - name: Print OS information
        shell: pwsh
        run: |
          echo "OS Name: $env:OS"
          echo "OS Version: $env:OS_VERSION"
          echo "OS Architecture: $env:PROCESSOR_ARCHITECTURE"

      - name: Print current directory
        shell: pwsh
        run: "echo 'Current directory: $env:GITHUB_WORKSPACE'"

      - name: Print environment variables
        shell: pwsh
        run: |
          echo "Environment Variables:"
          Get-ChildItem Env:
          foreach ($var in Get-ChildItem Env:) {
            Write-Host "$($var.Name) = $($var.Value)"
          }