name: Test Windows Self-Hosted Runner

on:
  workflow_dispatch:

jobs:
  test-windows:
    runs-on: [self-hosted, windows]
    steps:
      - name: Allow PowerShell script execution temporarily
        run: Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope Process -Force

      - name: Print runner info
        run: |
          echo "Runner Name: $env:RUNNER_NAME"
          echo "OS: $env:RUNNER_OS"
          echo "Arch: $env:RUNNER_ARCH"

      - name: Check PowerShell Version
        run: $PSVersionTable

      - name: List Files in C:\
        run: Get-ChildItem -Path C:\ -Force

      - name: Test File Write
        run: |
          $content = "Hello from GitHub Actions on $(hostname)"
          Set-Content -Path "$env:USERPROFILE\Desktop\test-runner.txt" -Value $content